/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NoOpfsRouteImport } from './routes/no-opfs'
import { Route as NoCoiRouteImport } from './routes/no-coi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetTokenRouteImport } from './routes/reset.$token'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppRecentsRouteImport } from './routes/_app/recents'
import { Route as AppLinksRouteImport } from './routes/_app/links'
import { Route as AppFavoritesRouteImport } from './routes/_app/favorites'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppSharedOutSplatRouteImport } from './routes/_app/shared-out.$'
import { Route as AppSharedInSplatRouteImport } from './routes/_app/shared-in.$'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app/settings/security'
import { Route as AppDriveSplatRouteImport } from './routes/_app/drive.$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NoOpfsRoute = NoOpfsRouteImport.update({
  id: '/no-opfs',
  path: '/no-opfs',
  getParentRoute: () => rootRouteImport,
} as any)
const NoCoiRoute = NoCoiRouteImport.update({
  id: '/no-coi',
  path: '/no-coi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTokenRoute = ResetTokenRouteImport.update({
  id: '/reset/$token',
  path: '/reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecentsRoute = AppRecentsRouteImport.update({
  id: '/recents',
  path: '/recents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLinksRoute = AppLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSharedOutSplatRoute = AppSharedOutSplatRouteImport.update({
  id: '/shared-out/$',
  path: '/shared-out/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSharedInSplatRoute = AppSharedInSplatRouteImport.update({
  id: '/shared-in/$',
  path: '/shared-in/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDriveSplatRoute = AppDriveSplatRouteImport.update({
  id: '/drive/$',
  path: '/drive/$',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-coi': typeof NoCoiRoute
  '/no-opfs': typeof NoOpfsRoute
  '/register': typeof RegisterRoute
  '/contacts': typeof AppContactsRoute
  '/favorites': typeof AppFavoritesRoute
  '/links': typeof AppLinksRoute
  '/recents': typeof AppRecentsRoute
  '/transfers': typeof AppTransfersRoute
  '/trash': typeof AppTrashRoute
  '/reset/$token': typeof ResetTokenRoute
  '/drive/$': typeof AppDriveSplatRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/shared-in/$': typeof AppSharedInSplatRoute
  '/shared-out/$': typeof AppSharedOutSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/no-coi': typeof NoCoiRoute
  '/no-opfs': typeof NoOpfsRoute
  '/register': typeof RegisterRoute
  '/contacts': typeof AppContactsRoute
  '/favorites': typeof AppFavoritesRoute
  '/links': typeof AppLinksRoute
  '/recents': typeof AppRecentsRoute
  '/transfers': typeof AppTransfersRoute
  '/trash': typeof AppTrashRoute
  '/reset/$token': typeof ResetTokenRoute
  '/drive/$': typeof AppDriveSplatRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/shared-in/$': typeof AppSharedInSplatRoute
  '/shared-out/$': typeof AppSharedOutSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/no-coi': typeof NoCoiRoute
  '/no-opfs': typeof NoOpfsRoute
  '/register': typeof RegisterRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/links': typeof AppLinksRoute
  '/_app/recents': typeof AppRecentsRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/trash': typeof AppTrashRoute
  '/reset/$token': typeof ResetTokenRoute
  '/_app/drive/$': typeof AppDriveSplatRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/shared-in/$': typeof AppSharedInSplatRoute
  '/_app/shared-out/$': typeof AppSharedOutSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-coi'
    | '/no-opfs'
    | '/register'
    | '/contacts'
    | '/favorites'
    | '/links'
    | '/recents'
    | '/transfers'
    | '/trash'
    | '/reset/$token'
    | '/drive/$'
    | '/settings/security'
    | '/shared-in/$'
    | '/shared-out/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-coi'
    | '/no-opfs'
    | '/register'
    | '/contacts'
    | '/favorites'
    | '/links'
    | '/recents'
    | '/transfers'
    | '/trash'
    | '/reset/$token'
    | '/drive/$'
    | '/settings/security'
    | '/shared-in/$'
    | '/shared-out/$'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/no-coi'
    | '/no-opfs'
    | '/register'
    | '/_app/contacts'
    | '/_app/favorites'
    | '/_app/links'
    | '/_app/recents'
    | '/_app/transfers'
    | '/_app/trash'
    | '/reset/$token'
    | '/_app/drive/$'
    | '/_app/settings/security'
    | '/_app/shared-in/$'
    | '/_app/shared-out/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoCoiRoute: typeof NoCoiRoute
  NoOpfsRoute: typeof NoOpfsRoute
  RegisterRoute: typeof RegisterRoute
  ResetTokenRoute: typeof ResetTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-opfs': {
      id: '/no-opfs'
      path: '/no-opfs'
      fullPath: '/no-opfs'
      preLoaderRoute: typeof NoOpfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-coi': {
      id: '/no-coi'
      path: '/no-coi'
      fullPath: '/no-coi'
      preLoaderRoute: typeof NoCoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$token': {
      id: '/reset/$token'
      path: '/reset/$token'
      fullPath: '/reset/$token'
      preLoaderRoute: typeof ResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/recents': {
      id: '/_app/recents'
      path: '/recents'
      fullPath: '/recents'
      preLoaderRoute: typeof AppRecentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/links': {
      id: '/_app/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AppLinksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shared-out/$': {
      id: '/_app/shared-out/$'
      path: '/shared-out/$'
      fullPath: '/shared-out/$'
      preLoaderRoute: typeof AppSharedOutSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shared-in/$': {
      id: '/_app/shared-in/$'
      path: '/shared-in/$'
      fullPath: '/shared-in/$'
      preLoaderRoute: typeof AppSharedInSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/drive/$': {
      id: '/_app/drive/$'
      path: '/drive/$'
      fullPath: '/drive/$'
      preLoaderRoute: typeof AppDriveSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppContactsRoute: typeof AppContactsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppLinksRoute: typeof AppLinksRoute
  AppRecentsRoute: typeof AppRecentsRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppTrashRoute: typeof AppTrashRoute
  AppDriveSplatRoute: typeof AppDriveSplatRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSharedInSplatRoute: typeof AppSharedInSplatRoute
  AppSharedOutSplatRoute: typeof AppSharedOutSplatRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppContactsRoute: AppContactsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppLinksRoute: AppLinksRoute,
  AppRecentsRoute: AppRecentsRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppTrashRoute: AppTrashRoute,
  AppDriveSplatRoute: AppDriveSplatRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSharedInSplatRoute: AppSharedInSplatRoute,
  AppSharedOutSplatRoute: AppSharedOutSplatRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NoCoiRoute: NoCoiRoute,
  NoOpfsRoute: NoOpfsRoute,
  RegisterRoute: RegisterRoute,
  ResetTokenRoute: ResetTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
