// Standard-unicode emoji shortcode table + lookup — the web's resolution of the emoji handling C1
// deferred (shortcodes rendered literal). Mobile ships a CUSTOM emoji pack (@/assets/customEmojis, a
// ~6000-line dataset of CDN-hosted .webp images); that pack is mobile-asset-bound (its skins are remote
// image URLs, not glyphs) and re-bundling it here would drag in an external image dependency the wasm
// build has no business fetching. Per the composer wave's brief, the web instead completes / renders
// against a curated STANDARD-unicode shortcode table (a subset of the gemoji/emoji-mart short-name
// convention): `:name:` completes to and renders as the native unicode glyph, self-contained and
// asset-free. Custom-pack-only shortcodes a peer sends from mobile/old-web still render as their literal
// `:shortcode:` (unknown here) — an accepted gap until the shared pack has a sanctioned web home.

// shortcode (without the surrounding colons) → unicode glyph. Curated common set; extend as needed.
export const EMOJI_SHORTCODES: Readonly<Record<string, string>> = {
	smile: "😄",
	smiley: "😃",
	grin: "😁",
	laughing: "😆",
	joy: "😂",
	rofl: "🤣",
	relaxed: "☺️",
	blush: "😊",
	slightly_smiling_face: "🙂",
	upside_down_face: "🙃",
	wink: "😉",
	heart_eyes: "😍",
	kissing_heart: "😘",
	kissing: "😗",
	yum: "😋",
	stuck_out_tongue: "😛",
	stuck_out_tongue_winking_eye: "😜",
	stuck_out_tongue_closed_eyes: "😝",
	money_mouth_face: "🤑",
	hugs: "🤗",
	thinking: "🤔",
	zipper_mouth_face: "🤐",
	neutral_face: "😐",
	expressionless: "😑",
	no_mouth: "😶",
	smirk: "😏",
	unamused: "😒",
	roll_eyes: "🙄",
	grimacing: "😬",
	relieved: "😌",
	pensive: "😔",
	sleepy: "😪",
	drooling_face: "🤤",
	sleeping: "😴",
	mask: "😷",
	face_with_thermometer: "🤒",
	nauseated_face: "🤢",
	sneezing_face: "🤧",
	dizzy_face: "😵",
	sunglasses: "😎",
	nerd_face: "🤓",
	confused: "😕",
	worried: "😟",
	slightly_frowning_face: "🙁",
	frowning_face: "☹️",
	open_mouth: "😮",
	hushed: "😯",
	astonished: "😲",
	flushed: "😳",
	frowning: "😦",
	anguished: "😧",
	fearful: "😨",
	cold_sweat: "😰",
	disappointed_relieved: "😥",
	cry: "😢",
	sob: "😭",
	scream: "😱",
	confounded: "😖",
	persevere: "😣",
	disappointed: "😞",
	sweat: "😓",
	weary: "😩",
	tired_face: "😫",
	triumph: "😤",
	rage: "😡",
	angry: "😠",
	smiling_imp: "😈",
	imp: "👿",
	skull: "💀",
	poop: "💩",
	clown_face: "🤡",
	ghost: "👻",
	alien: "👽",
	robot: "🤖",
	wave: "👋",
	raised_hand: "✋",
	ok_hand: "👌",
	v: "✌️",
	crossed_fingers: "🤞",
	point_up: "☝️",
	point_down: "👇",
	point_left: "👈",
	point_right: "👉",
	thumbsup: "👍",
	"+1": "👍",
	thumbsdown: "👎",
	"-1": "👎",
	fist: "✊",
	facepunch: "👊",
	clap: "👏",
	raised_hands: "🙌",
	pray: "🙏",
	handshake: "🤝",
	muscle: "💪",
	writing_hand: "✍️",
	nail_care: "💅",
	eyes: "👀",
	brain: "🧠",
	heart: "❤️",
	orange_heart: "🧡",
	yellow_heart: "💛",
	green_heart: "💚",
	blue_heart: "💙",
	purple_heart: "💜",
	black_heart: "🖤",
	broken_heart: "💔",
	two_hearts: "💕",
	sparkling_heart: "💖",
	heartpulse: "💗",
	cupid: "💘",
	fire: "🔥",
	star: "⭐",
	star2: "🌟",
	sparkles: "✨",
	zap: "⚡",
	boom: "💥",
	collision: "💥",
	dizzy: "💫",
	sweat_drops: "💦",
	droplet: "💧",
	tada: "🎉",
	confetti_ball: "🎊",
	balloon: "🎈",
	gift: "🎁",
	trophy: "🏆",
	medal: "🏅",
	rocket: "🚀",
	airplane: "✈️",
	sunny: "☀️",
	cloud: "☁️",
	rainbow: "🌈",
	snowflake: "❄️",
	snowman: "⛄",
	moon: "🌙",
	earth_africa: "🌍",
	dog: "🐶",
	cat: "🐱",
	mouse: "🐭",
	rabbit: "🐰",
	fox_face: "🦊",
	bear: "🐻",
	panda_face: "🐼",
	tiger: "🐯",
	lion: "🦁",
	cow: "🐮",
	pig: "🐷",
	frog: "🐸",
	monkey_face: "🐵",
	chicken: "🐔",
	penguin: "🐧",
	bird: "🐦",
	unicorn: "🦄",
	bee: "🐝",
	bug: "🐛",
	butterfly: "🦋",
	snail: "🐌",
	fish: "🐟",
	whale: "🐳",
	dolphin: "🐬",
	apple: "🍎",
	banana: "🍌",
	pizza: "🍕",
	hamburger: "🍔",
	fries: "🍟",
	taco: "🌮",
	coffee: "☕",
	tea: "🍵",
	beer: "🍺",
	beers: "🍻",
	wine_glass: "🍷",
	cocktail: "🍸",
	cake: "🍰",
	birthday: "🎂",
	cookie: "🍪",
	chocolate_bar: "🍫",
	candy: "🍬",
	doughnut: "🍩",
	ice_cream: "🍨",
	checkered_flag: "🏁",
	soccer: "⚽",
	basketball: "🏀",
	football: "🏈",
	tennis: "🎾",
	"8ball": "🎱",
	game_die: "🎲",
	dart: "🎯",
	musical_note: "🎵",
	notes: "🎶",
	microphone: "🎤",
	headphones: "🎧",
	guitar: "🎸",
	bulb: "💡",
	computer: "💻",
	iphone: "📱",
	email: "📧",
	lock: "🔒",
	key: "🔑",
	hourglass: "⌛",
	watch: "⌚",
	bell: "🔔",
	mag: "🔍",
	link: "🔗",
	pushpin: "📌",
	memo: "📝",
	pencil: "📝",
	book: "📖",
	books: "📚",
	moneybag: "💰",
	dollar: "💵",
	credit_card: "💳",
	gem: "💎",
	white_check_mark: "✅",
	heavy_check_mark: "✔️",
	x: "❌",
	negative_squared_cross_mark: "❎",
	warning: "⚠️",
	no_entry: "⛔",
	question: "❓",
	exclamation: "❗",
	bangbang: "‼️",
	100: "💯",
	ok: "🆗",
	new: "🆕",
	up: "🔼",
	arrow_up: "⬆️",
	arrow_down: "⬇️",
	arrow_left: "⬅️",
	arrow_right: "➡️",
	recycle: "♻️",
	heavy_plus_sign: "➕",
	heavy_minus_sign: "➖",
	heavy_multiplication_x: "✖️",
	heavy_dollar_sign: "💲",
	white_flower: "💮",
	rose: "🌹",
	sunflower: "🌻",
	four_leaf_clover: "🍀",
	christmas_tree: "🎄",
	jack_o_lantern: "🎃",
	crown: "👑",
	eyeglasses: "👓",
	tophat: "🎩",
	umbrella: "☂️",
	house: "🏠",
	office: "🏢",
	hospital: "🏥",
	school: "🏫",
	car: "🚗",
	taxi: "🚕",
	bus: "🚌",
	train: "🚆",
	bike: "🚲",
	anchor: "⚓",
	construction: "🚧",
	hammer: "🔨",
	wrench: "🔧",
	gear: "⚙️",
	shield: "🛡️",
	battery: "🔋",
	flashlight: "🔦",
	camera: "📷",
	tv: "📺",
	clapper: "🎬",
	art: "🎨",
	dizzy_star: "🌠",
	partying_face: "🥳",
	exploding_head: "🤯",
	shushing_face: "🤫",
	star_struck: "🤩",
	heart_hands: "🫶",
	saluting_face: "🫡",
	melting_face: "🫠"
}

// Longest-name-first isn't needed — shortcodes are looked up whole. Returns the glyph or undefined.
export function emojiForShortcode(shortcode: string): string | undefined {
	return EMOJI_SHORTCODES[shortcode.toLowerCase()]
}

export interface EmojiSuggestion {
	name: string
	char: string
}

// Suggestion list for the composer's `:` autocomplete. Prefix matches rank above substring matches
// (both alphabetically inside their tier), so `:sm` surfaces `smile`/`smiley` before `kissing_heart`
// never would — it just keeps the obvious completions on top. Capped to `limit` (mobile caps at 10).
export function searchEmoji(query: string, limit: number): EmojiSuggestion[] {
	const q = query.toLowerCase()

	if (q.length === 0) {
		return []
	}

	const prefix: EmojiSuggestion[] = []
	const contains: EmojiSuggestion[] = []

	for (const name of Object.keys(EMOJI_SHORTCODES)) {
		const char = EMOJI_SHORTCODES[name]

		if (char === undefined) {
			continue
		}

		if (name.startsWith(q)) {
			prefix.push({ name, char })
		} else if (name.includes(q)) {
			contains.push({ name, char })
		}
	}

	prefix.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
	contains.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))

	return [...prefix, ...contains].slice(0, limit)
}
