import { readFileSync, writeFileSync } from "node:fs"

// Codegen the SDK's `ErrorKind` string union into a runtime-checkable array so app code can
// map `FilenSdkError.kind` without a hand-maintained list (mobile's hand-map silently drifted).
// CI re-runs this + `git diff --exit-code` so the generated file can never go stale.
const dts = readFileSync("node_modules/@filen/sdk-rs/sdk-rs.d.ts", "utf8")
const union = /type ErrorKind =([^;]+);/.exec(dts)?.[1]
if (union === undefined || union === "") {
	throw new Error("ErrorKind union not found — .d.ts layout changed; update the regex")
}
const kinds: string[] = []
for (const match of union.matchAll(/"([A-Za-z0-9]+)"/g)) {
	const name = match[1]
	if (name !== undefined) {
		kinds.push(name)
	}
}
if (kinds.length === 0) {
	throw new Error("ErrorKind union empty")
}
writeFileSync(
	"src/lib/sdk/error-kinds.gen.ts",
	`// AUTO-GENERATED by scripts/gen-error-kinds.ts from @filen/sdk-rs@0.4.29 — do not edit.\n` +
		`export const ERROR_KINDS = ${JSON.stringify(kinds, null, "\t")} as const\n` +
		`export type SdkErrorKind = (typeof ERROR_KINDS)[number]\n`
)
console.log(`error-kinds: ${String(kinds.length)} kinds`)
