import { runTimeout, driveItemName } from "@filen/shared"
import type { File as SdkFile } from "@filen/sdk-rs"
import { sdkApi } from "@/lib/sdk/client"
import { runOp } from "@/lib/actions/outcome"
import { log } from "@/lib/log"
import { narrowToAnyFile } from "@/features/drive/lib/download"
import { registerThumbGenerator, seedThumbnail, type ThumbGenerationResult, type ThumbGenerator } from "@/features/drive/lib/thumbnails"
import {
	THUMB_MAX_DIM,
	THUMB_SDK_MAX_HEIGHT,
	THUMB_SDK_LOSSY_QUALITY,
	THUMB_WARM_SIZE_GATE,
	thumbnailCategory
} from "@/features/drive/lib/thumbnails.logic"
import { fitWithin, encodeCanvasThumb } from "@/features/drive/lib/thumbGenerators.logic"
import { previewStreamUrl, waitForMediaStream } from "@/features/preview/lib/previewStream"
import { allowedMediaContentType } from "@/features/preview/lib/mediaType"
import { narrowItem, type BaseFileItem } from "@/features/drive/lib/item"
import type { SdkThumbnailResult } from "@/workers/sdk.worker"

// pdf is the one generator left that pulls a whole file into JS memory, through the same buffered
// download the preview overlay uses (usePreviewBytes). There is no unmount to hook a cancellation
// into here (a generator is a one-shot promise the service's own Semaphore/dedupe gate around, not a
// component) so the minted token only ever satisfies downloadFileBytes' own signature — the worker's
// previewAborts entry for it is dropped on this same call's own settle regardless of whether anything
// ever calls cancelPreviewDownload.
async function downloadWholeFile(item: BaseFileItem): Promise<Uint8Array> {
	const file = narrowToAnyFile(item)
	const token = crypto.randomUUID()

	return await runOp(sdkApi.downloadFileBytes(file, token))
}

// Persisting the generated bytes (storeThumbnail) is NOT a generator's job — features/drive/lib/thumbnails.ts's
// own generate() already does that once, uniformly, for whatever any registered generator returns. A
// second persist call here would double-write the same uuid to OPFS on every generated thumbnail.

// Maps the worker DTO onto the service's own three-way result. The three byte-less arms are SETTLED
// verdicts about the file's content, so they become "unavailable" (remembered for the session, no
// blacklist strike) rather than the plain failure a dropped call is. An empty buffer is treated as a
// failure, not a verdict — bytes that claim to be a thumbnail but aren't are a bug somewhere, and the
// blacklist is the right place for it.
function asGenerationResult(result: SdkThumbnailResult): ThumbGenerationResult {
	if (result.type === "thumbnail") {
		return result.bytes.length === 0 ? { type: "failed" } : { type: "bytes", bytes: result.bytes }
	}

	return { type: "unavailable", reason: result.type }
}

// EVERY still image on the drive — plain raster, HEIC and camera RAW alike — decoded by the Rust SDK.
// Nothing is downloaded into JS: the SDK reads the ranges it needs itself (the cheap embedded-preview
// probe first, at worst a whole-file range read inside wasm), and only the small webp result crosses
// back. That is the whole point of routing RAW here — a 90 MB NEF usually costs a couple of range
// reads because the camera already embedded a full-size JPEG in it.
//
// The request is 384x768 rather than square, and lossy; THUMB_SDK_MAX_HEIGHT and
// THUMB_SDK_LOSSY_QUALITY carry the reasoning for the shape and the encode respectively.
//
// A thrown call (the worker died, the client is gone, the read never landed) is a transient failure
// and counts toward the blacklist; the SDK's own unsupported/overBudget/corrupt answers do not.
export const generateSdkThumb: ThumbGenerator = async item => {
	try {
		const result = await sdkApi.makeSdkThumbnail(narrowToAnyFile(item), THUMB_MAX_DIM, THUMB_SDK_MAX_HEIGHT, THUMB_SDK_LOSSY_QUALITY)

		return asGenerationResult(result)
	} catch (e) {
		log.warn("thumb-generators", "generateSdkThumb: sdk call failed", item.data.uuid, e)

		return { type: "failed" }
	}
}

// Thumbnails a file the client STILL HOLDS, straight after its upload lands, so the freshly-patched
// listing row never triggers a download of bytes that are already on this machine. Seeded into the
// thumbnail service (seedThumbnail) rather than merely written to OPFS: the row's tile asks for its
// thumbnail in the very next commit, and only a pending-map entry makes that tile JOIN this
// production instead of racing it with a server-side one.
//
// Gated on thumbnailCategory of the uploaded file, not on a local extension guess — that keeps the
// SDK's own canMakeThumbnail as the single source of truth here too, and drops video/pdf/svg (whose
// thumbnails are somebody else's job) for free.
//
// Sequenced AFTER the upload resolves, never overlapped with it. Both legs read the same browser File
// through their own `.stream()`, and a Blob hands out a FRESH ReadableStream per call, so an overlap
// would be correct but would have the SDK reading the same local file twice at once for no gain.
// Synchronous and fire-and-forget by design: the transfer is already settled and the row is already
// in the listing, so blocking either on a cache warm would only delay the upload summary toast.
export function warmUploadThumbnail(uploaded: SdkFile, file: File): void {
	const item = narrowItem(uploaded)

	if (thumbnailCategory(item) !== "sdk") {
		return
	}

	// Size-gated where the drive-side arm deliberately is not, because the two arms do not decode under
	// the same budget: makeThumbnailFromStream buffers the source WHOLE and takes its length off the
	// SDK's decode budget, where the drive arm pays a constant three chunk slots for a source it reads by
	// range. Past THUMB_WARM_SIZE_GATE what is left cannot afford the 256x512 this asks for, and the
	// result is not a refusal but a SMALLER thumbnail — which the seat then persists as the uuid's
	// durable cache entry, displacing the full-size one the drive arm would have produced. A browser
	// File knows its own size, so nothing is read to decide this.
	if (BigInt(file.size) > THUMB_WARM_SIZE_GATE) {
		return
	}

	seedThumbnail(item, async () => {
		const result = await sdkApi.makeSdkThumbnailFromFile(file, THUMB_MAX_DIM, THUMB_SDK_MAX_HEIGHT, THUMB_SDK_LOSSY_QUALITY)

		if (result.type === "thumbnail") {
			return { type: "bytes", bytes: result.bytes }
		}

		log.info("thumb-generators", "warmUploadThumbnail: no thumbnail", uploaded.uuid, result.type)

		// `unsupported` and `corrupt` are answers about the bytes themselves, which the drive-side arm
		// sniffs the same way and would answer the same. `overBudget` is not: the budget this arm decodes
		// under shrank by the whole source, so a decoder peak that does not fit HERE can still fit the
		// drive arm's near-full budget — a verdict about this arm's own buffering, not about the file.
		return result.type === "overBudget" ? { type: "unanswered" } : { type: "none" }
	})
}

// Resolves once `event` fires, or rejects if the element errors first — a corrupt/unplayable stream
// must fail promptly rather than sit until runTimeout's own ceiling.
function waitForVideoEvent(video: HTMLVideoElement, event: "loadeddata" | "seeked"): Promise<void> {
	return new Promise((resolve, reject) => {
		const cleanup = () => {
			video.removeEventListener(event, onEvent)
			video.removeEventListener("error", onError)
		}
		const onEvent = () => {
			cleanup()
			resolve()
		}
		const onError = () => {
			cleanup()
			reject(new Error(`video element errored before ${event}`))
		}

		video.addEventListener(event, onEvent, { once: true })
		video.addEventListener("error", onError, { once: true })
	})
}

const VIDEO_GENERATE_TIMEOUT_MS = 15_000

// isMediaStreamAvailable/allowedMediaContentType are cheap synchronous gates checked BEFORE the
// runTimeout below, so an environment that can never stream (SW not yet controlling the tab, or an
// item whose own mime never clears the inline allowlist) fails instantly instead of occupying a
// semaphore slot for the full 15s ceiling for no reason.
export const generateVideoThumb: ThumbGenerator = async item => {
	// Awaited rather than sampled: this frame comes off the SW's Range stream, and a page is
	// uncontrolled for a moment after every worker install or update — the ordinary state of a first
	// load. Sampling it there returned "failed", which counts toward the blacklist, so scrolling a
	// directory of videos in that window could spend all three strikes and leave them blank for the
	// rest of the session even once the worker took control. Where no worker is registered at all it
	// still returns immediately, so nothing ever waits for a stream that is not coming.
	if (!(await waitForMediaStream())) {
		return { type: "failed" }
	}

	const contentType = allowedMediaContentType(item)

	if (contentType === null) {
		return { type: "failed" }
	}

	// runTimeout races a timer against this whole callback but cannot actually abort a still-running
	// video/event-listener chain if it loses the race (verified against @filen/shared' own
	// implementation: the deferred cleanup below only runs once THIS callback itself settles) — an
	// unplayable stream that never fires loadeddata/seeked/error leaves a listener chain pending in
	// the background past the 15s return. That is an accepted, bounded cost: the SW's own pending-
	// registration table is capped at 32 entries and oldest-evicts, so it cannot accumulate across a
	// session even if this happens repeatedly.
	const result = await runTimeout(async defer => {
		const file = narrowToAnyFile(item)
		const name = driveItemName(item)
		const url = await previewStreamUrl(file, name, contentType)

		const video = document.createElement("video")

		video.muted = true
		video.playsInline = true
		video.preload = "auto"
		video.src = url

		defer(() => {
			video.src = ""
			video.load()
		})

		await waitForVideoEvent(video, "loadeddata")

		// An indeterminate duration (NaN — e.g. a stream with no known Content-Length) falls back to
		// frame 0, which is already showing once loadeddata fires: seeking to the position the video is
		// already at would never fire `seeked`, hanging until the outer timeout.
		const seekTo = Number.isFinite(video.duration) ? Math.min(1, video.duration / 2) : 0

		if (seekTo > 0) {
			video.currentTime = seekTo

			await waitForVideoEvent(video, "seeked")
		}

		const { width, height } = fitWithin(video.videoWidth, video.videoHeight, THUMB_MAX_DIM)
		const canvas = new OffscreenCanvas(width, height)
		const ctx = canvas.getContext("2d")

		if (ctx === null) {
			throw new Error("could not create an OffscreenCanvas 2D context")
		}

		ctx.drawImage(video, 0, 0, width, height)

		const blob = await encodeCanvasThumb(canvas)

		return new Uint8Array(await blob.arrayBuffer())
	}, VIDEO_GENERATE_TIMEOUT_MS)

	if (!result.success) {
		log.warn("thumb-generators", "generateVideoThumb failed", item.data.uuid, result.error)

		return { type: "failed" }
	}

	return { type: "bytes", bytes: result.data }
}

export const generatePdfThumb: ThumbGenerator = async item => {
	let bytes: Uint8Array

	try {
		bytes = await downloadWholeFile(item)
	} catch (e) {
		log.warn("thumb-generators", "generatePdfThumb: download failed", item.data.uuid, e)

		return { type: "failed" }
	}

	// Lazy: keeps pdf.js's ~1 MB bundle out of every session that never opens or generates a PDF
	// thumbnail — pdfViewer.tsx can import it statically because that whole component is itself
	// route/lazy-split, which this plain module is not.
	const { getDocument, GlobalWorkerOptions } = await import("pdfjs-dist")

	// Mirrors pdfViewer.tsx's own worker-src setup (duplicated rather than imported: that file is a
	// React component this module must not depend on). A STRING workerSrc gives every getDocument()
	// call its own dedicated worker, so this task's destroy() below can never tear down a document a
	// concurrent preview or generation still has open.
	GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.mjs", import.meta.url).href

	const task = getDocument({ data: bytes })

	try {
		// No onPassword handler is registered — pdf.js rejects task.promise with the password exception
		// instead of waiting on a handler that will never answer (verified against the installed 6.1.200
		// source), so a password-protected file fails this generation promptly rather than hanging.
		const doc = await task.promise
		const page = await doc.getPage(1)
		const baseViewport = page.getViewport({ scale: 1 })
		const fitted = fitWithin(baseViewport.width, baseViewport.height, THUMB_MAX_DIM)
		const viewport = page.getViewport({ scale: fitted.width / baseViewport.width })

		const canvas = document.createElement("canvas")

		canvas.width = fitted.width
		canvas.height = fitted.height

		const renderTask = page.render({ canvas, viewport })

		await renderTask.promise

		const blob = await encodeCanvasThumb(canvas)

		return { type: "bytes", bytes: new Uint8Array(await blob.arrayBuffer()) }
	} catch (e) {
		log.warn("thumb-generators", "generatePdfThumb: render failed", item.data.uuid, e)

		return { type: "failed" }
	} finally {
		await task.destroy()
	}
}

// Module scope, not inside a function: runs exactly once per module evaluation (mirrors
// the drive.newDirectory def in features/drive/lib/keymap.ts). features/drive/lib/thumbnails.ts (the service)
// deliberately never imports this module itself — it already exposes registerThumbGenerator as a
// seam specifically so it doesn't need to know these generators exist, and importing back would cycle
// — so whichever consumer wants thumbnails (sdk/video/pdf) must import this module at least once,
// even just for this side effect, before requesting one; until then getThumbnailUrl's own
// unregistered-category path (a clean null, never a throw) is all any item resolves to.
registerThumbGenerator("sdk", generateSdkThumb)
registerThumbGenerator("video", generateVideoThumb)
registerThumbGenerator("pdf", generatePdfThumb)
