import { runTimeout, driveItemName, Semaphore, type DeferFn, type Result } from "@filen/shared"
import type { File as SdkFile } from "@filen/sdk-rs"
import { sdkApi } from "@/lib/sdk/client"
import { runOp } from "@/lib/actions/outcome"
import { log } from "@/lib/log"
import { narrowToAnyFile } from "@/features/drive/lib/download"
import {
	registerThumbGenerator,
	seedThumbnail,
	withGenerationSlot,
	type ThumbGenerationResult,
	type ThumbGenerator,
	type ThumbSeedResult
} from "@/features/drive/lib/thumbnails"
import {
	THUMB_MAX_DIM,
	THUMB_SDK_MAX_HEIGHT,
	THUMB_SDK_LOSSY_QUALITY,
	THUMB_WARM_SIZE_GATE,
	thumbnailCategory
} from "@/features/drive/lib/thumbnails.logic"
import { fitWithin, encodeCanvasThumb } from "@/features/drive/lib/thumbGenerators.logic"
import { prepareSvgThumb } from "@/features/drive/lib/svgThumb.logic"
import { previewStreamUrl, waitForMediaStream } from "@/features/preview/lib/previewStream"
import { allowedMediaContentType } from "@/features/preview/lib/mediaType"
import { narrowItem, type BaseFileItem, type DriveItem } from "@/features/drive/lib/item"
import type { SdkThumbnailResult } from "@/workers/sdk.worker"
import { getDocument, GlobalWorkerOptions, PDFWorker } from "pdfjs-dist"
import { idleResource, type IdleResource } from "@/lib/idleResource"
import { recoverIfNewerBuild } from "@/lib/appUpdate"
import { getPreviewBytes } from "@/features/preview/lib/previewCache"
import { previewCacheScope } from "@/features/preview/lib/accessMode"

// Past this share of its bytes, a download whose thumbnail nobody wants any more finishes anyway: the
// rest costs less than starting over the next time the cell scrolls into view.
const DOWNLOAD_COMMIT_FRACTION = 0.5

// pdf and svg are the generators that pull a whole file into JS memory, through the same buffered
// download the preview overlay uses (usePreviewBytes) — or straight from the bytes a preview already
// holds. The returned buffer is the caller's own, so a consumer may transfer it.
async function downloadWholeFile(item: BaseFileItem, signal: AbortSignal): Promise<Uint8Array> {
	const held = getPreviewBytes(previewCacheScope("authed", undefined), item.data.uuid)

	if (held !== undefined) {
		return held.slice()
	}

	signal.throwIfAborted()

	const token = crypto.randomUUID()
	const stop = (): void => {
		void sdkApi.cancelPreviewDownloadIfEarly(token, DOWNLOAD_COMMIT_FRACTION)
	}

	signal.addEventListener("abort", stop, { once: true })

	try {
		return await runOp(sdkApi.downloadFileBytes(narrowToAnyFile(item), token))
	} finally {
		signal.removeEventListener("abort", stop)
	}
}

// Persisting the generated bytes (storeThumbnail) is NOT a generator's job — features/drive/lib/thumbnails.ts's
// own generate() already does that once, uniformly, for whatever any registered generator returns. A
// second persist call here would double-write the same uuid to OPFS on every generated thumbnail.

// Maps the worker DTO onto the service's own three-way result. The three byte-less arms are SETTLED
// verdicts about the file's content, so they become "unavailable" (remembered for the session, no
// blacklist strike) rather than the plain failure a dropped call is. An empty buffer is treated as a
// failure, not a verdict — bytes that claim to be a thumbnail but aren't are a bug somewhere, and the
// blacklist is the right place for it.
function asGenerationResult(result: SdkThumbnailResult): ThumbGenerationResult {
	if (result.type === "thumbnail") {
		return result.bytes.length === 0 ? { type: "failed" } : { type: "bytes", bytes: result.bytes }
	}

	return { type: "unavailable", reason: result.type }
}

// EVERY still image on the drive — plain raster, HEIC and camera RAW alike — decoded by the Rust SDK.
// Nothing is downloaded into JS: the SDK reads the ranges it needs itself (the cheap embedded-preview
// probe first, at worst a whole-file range read inside wasm), and only the small webp result crosses
// back. That is the whole point of routing RAW here — a 90 MB NEF usually costs a couple of range
// reads because the camera already embedded a full-size JPEG in it.
//
// The request is 384x768 rather than square, and lossy; THUMB_SDK_MAX_HEIGHT and
// THUMB_SDK_LOSSY_QUALITY carry the reasoning for the shape and the encode respectively.
//
// A thrown call (the worker died, the client is gone, the read never landed) is a transient failure
// and counts toward the blacklist; the SDK's own unsupported/overBudget/corrupt answers do not.
//
// Never stopped once started: the SDK's in-memory thumbnail call takes no ManagedFuture, and it is
// usually a couple of range reads anyway.
export const generateSdkThumb: ThumbGenerator = async item => {
	try {
		const result = await sdkApi.makeSdkThumbnail(narrowToAnyFile(item), THUMB_MAX_DIM, THUMB_SDK_MAX_HEIGHT, THUMB_SDK_LOSSY_QUALITY)

		return asGenerationResult(result)
	} catch (e) {
		log.warn("thumb-generators", "generateSdkThumb: sdk call failed", item.data.uuid, e)

		return { type: "failed" }
	}
}

// Thumbnails a file the client STILL HOLDS, straight after its upload lands, so the freshly-patched
// listing row never triggers a download of bytes that are already on this machine. Seeded into the
// thumbnail service (seedThumbnail) rather than merely written to OPFS: the row's tile asks for its
// thumbnail in the very next commit, and only a pending-map entry makes that tile JOIN this
// production instead of racing it with a server-side one.
//
// Gated on thumbnailCategory of the uploaded file, not on a local extension guess — that keeps the
// SDK's own canMakeThumbnail as the single source of truth here too. An svg, a video and a pdf are
// made here too, by the very code the drive-side arm runs, from the local file instead of a download.
//
// Sequenced AFTER the upload resolves, never overlapped with it: both legs read the same browser File,
// and an overlap would be correct but would read the same local file twice at once for no gain.
// Synchronous and fire-and-forget by design: the transfer is already settled and the row is already
// in the listing, so blocking either on a cache warm would only delay the upload summary toast.
export function warmUploadThumbnail(uploaded: SdkFile, file: File): void {
	const item = narrowItem(uploaded)
	const category = thumbnailCategory(item)

	// Its size gate is already in the category. The rasteriser's verdicts are about the markup itself,
	// which the drive-side arm would read identically; only a failure leaves the uuid to it.
	if (category === "svg") {
		seedThumbnail(item, async () => {
			const result = await rasterizeSvgThumb(await file.text())

			return result.type === "bytes" ? result : { type: result.type === "unavailable" ? "none" : "unanswered" }
		})

		return
	}

	if (category === "video") {
		// Typed as the drive-side arm's stream is; a same-type slice is a view of the File, not a copy. An
		// item that arm would never stream gets no seat: it fails there without a request.
		const contentType = allowedMediaContentType(item)

		if (contentType !== null) {
			seedLocalThumb(item, "video", () =>
				videoThumb(uploaded.uuid, defer => {
					const url = URL.createObjectURL(file.slice(0, file.size, contentType))

					defer(() => {
						URL.revokeObjectURL(url)
					})

					return url
				})
			)
		}

		return
	}

	if (category === "pdf") {
		seedLocalThumb(item, "pdf", async () => {
			let bytes: Uint8Array

			try {
				bytes = new Uint8Array(await file.arrayBuffer())
			} catch (e) {
				log.warn("thumb-generators", "warmUploadThumbnail: local read failed", uploaded.uuid, e)

				return null
			}

			return await renderPdfThumb(bytes, uploaded.uuid)
		})

		return
	}

	if (category !== "sdk") {
		return
	}

	// Size-gated where the drive-side arm deliberately is not, because the two arms do not decode under
	// the same budget: makeThumbnailFromStream buffers the source WHOLE and takes its length off the
	// SDK's decode budget, where the drive arm pays a constant three chunk slots for a source it reads by
	// range. Past THUMB_WARM_SIZE_GATE what is left cannot afford the 256x512 this asks for, and the
	// result is not a refusal but a SMALLER thumbnail — which the seat then persists as the uuid's
	// durable cache entry, displacing the full-size one the drive arm would have produced. A browser
	// File knows its own size, so nothing is read to decide this.
	if (BigInt(file.size) > THUMB_WARM_SIZE_GATE) {
		return
	}

	// In an image generation slot: it takes the SDK's decoder exactly as the drive-side arm would.
	seedThumbnail(item, () =>
		withGenerationSlot("sdk", async (): Promise<ThumbSeedResult> => {
			const result = await sdkApi.makeSdkThumbnailFromFile(file, THUMB_MAX_DIM, THUMB_SDK_MAX_HEIGHT, THUMB_SDK_LOSSY_QUALITY)

			if (result.type === "thumbnail") {
				return { type: "bytes", bytes: result.bytes }
			}

			log.info("thumb-generators", "warmUploadThumbnail: no thumbnail", uploaded.uuid, result.type)

			// `unsupported` and `corrupt` are answers about the bytes themselves, which the drive-side arm
			// sniffs the same way and would answer the same. `overBudget` is not: the budget this arm decodes
			// under shrank by the whole source, so a decoder peak that does not fit HERE can still fit the
			// drive arm's near-full budget — a verdict about this arm's own buffering, not about the file.
			return result.type === "overBudget" ? { type: "unanswered" } : { type: "none" }
		})
	)
}

// A local video or pdf production: a browser decode, so it takes a generation slot like the drive-side
// one it replaces (see withGenerationSlot). Its failure is settled as "none": the drive-side arm would
// run this same code over these same bytes, only after downloading them. Null is a local file that
// could not be read, which says nothing about the file.
function seedLocalThumb(item: DriveItem, category: "video" | "pdf", produce: () => Promise<ThumbGenerationResult | null>): void {
	seedThumbnail(item, () =>
		withGenerationSlot(category, async (): Promise<ThumbSeedResult> => {
			const result = await produce()

			if (result === null) {
				return { type: "unanswered" }
			}

			return result.type === "bytes" ? result : { type: "none" }
		})
	)
}

// Resolves once `event` fires, or rejects if the element errors first — a corrupt/unplayable stream
// must fail promptly rather than sit until the deadline — or once `signal` aborts.
function waitForVideoEvent(video: HTMLVideoElement, event: "loadedmetadata" | "loadeddata" | "seeked", signal: AbortSignal): Promise<void> {
	return new Promise((resolve, reject) => {
		const cleanup = () => {
			video.removeEventListener(event, onEvent)
			video.removeEventListener("error", onError)
			signal.removeEventListener("abort", onAbort)
		}
		const onEvent = () => {
			cleanup()
			resolve()
		}
		const onError = () => {
			cleanup()
			reject(new Error(`video element errored before ${event}`))
		}
		const onAbort = () => {
			cleanup()
			reject(new Error(`stopped waiting for ${event}`, { cause: signal.reason }))
		}

		if (signal.aborted) {
			onAbort()

			return
		}

		video.addEventListener(event, onEvent, { once: true })
		video.addEventListener("error", onError, { once: true })
		signal.addEventListener("abort", onAbort, { once: true })
	})
}

const VIDEO_GENERATE_TIMEOUT_MS = 15_000

// One frame of the video `openSource` resolves to, drawn into a thumbnail. Both arms share it: the
// drive-side one plays the SW's Range stream, the upload warm the local file.
//
// Only the metadata is preloaded, and the seek then fetches just the data for the frame drawn: buffering
// ahead ("auto") downloaded and decrypted megabytes that the teardown below then cancelled. The waits end
// at the deadline themselves, so a stream that never fires its event or error settles this callback and
// its deferred cleanup empties the element, ending the stream; runTimeout alone could only stop waiting
// for it. `signal` stops the generation only until the frame has loaded: past that, all that is left is
// one draw.
async function videoThumb(
	uuid: string,
	openSource: (defer: DeferFn) => Promise<string> | string,
	signal?: AbortSignal
): Promise<ThumbGenerationResult> {
	const deadline = AbortSignal.timeout(VIDEO_GENERATE_TIMEOUT_MS)
	const beforeFirstFrame = signal === undefined ? deadline : AbortSignal.any([signal, deadline])

	const result: Result<Uint8Array> = await runTimeout(async defer => {
		beforeFirstFrame.throwIfAborted()

		const url = await openSource(defer)

		const video = document.createElement("video")

		video.muted = true
		video.playsInline = true
		video.preload = "metadata"
		video.src = url

		// Removing the attribute empties the element. `src = ""` instead resolves against the page, so
		// Firefox loads the site root as media (and the service worker reports the failed load).
		defer(() => {
			video.removeAttribute("src")
			video.load()
		})

		await waitForVideoEvent(video, "loadedmetadata", beforeFirstFrame)

		// `seeked` fires once the frame at the new position is decoded. An indeterminate duration (NaN —
		// e.g. a stream with no known Content-Length) falls back to frame 0, where seeking to the position
		// the video is already at would never fire `seeked`: that one loads the first frame instead, which
		// a metadata-only preload need not do on its own.
		const seekTo = Number.isFinite(video.duration) ? Math.min(1, video.duration / 2) : 0

		if (seekTo > 0) {
			video.currentTime = seekTo

			await waitForVideoEvent(video, "seeked", beforeFirstFrame)
		} else if (video.readyState < video.HAVE_CURRENT_DATA) {
			video.preload = "auto"

			await waitForVideoEvent(video, "loadeddata", beforeFirstFrame)
		}

		const { width, height } = fitWithin(video.videoWidth, video.videoHeight, THUMB_MAX_DIM)
		const canvas = new OffscreenCanvas(width, height)
		const ctx = canvas.getContext("2d")

		if (ctx === null) {
			throw new Error("could not create an OffscreenCanvas 2D context")
		}

		ctx.drawImage(video, 0, 0, width, height)

		const blob = await encodeCanvasThumb(canvas)

		return new Uint8Array(await blob.arrayBuffer())
	}, VIDEO_GENERATE_TIMEOUT_MS)

	if (!result.success) {
		if (signal?.aborted !== true) {
			log.warn("thumb-generators", "videoThumb failed", uuid, result.error)
		}

		return { type: "failed" }
	}

	return { type: "bytes", bytes: result.data }
}

// isMediaStreamAvailable/allowedMediaContentType are cheap synchronous gates checked BEFORE the
// runTimeout in videoThumb, so an environment that can never stream (SW not yet controlling the tab,
// or an item whose own mime never clears the inline allowlist) fails instantly instead of occupying a
// semaphore slot for the full 15s ceiling for no reason.
export const generateVideoThumb: ThumbGenerator = async (item, signal) => {
	// Awaited rather than sampled: this frame comes off the SW's Range stream, and a page is
	// uncontrolled for a moment after every worker install or update — the ordinary state of a first
	// load. Sampling it there returned "failed", which counts toward the blacklist, so scrolling a
	// directory of videos in that window could spend all three strikes and leave them blank for the
	// rest of the session even once the worker took control. Where no worker is registered at all it
	// still returns immediately, so nothing ever waits for a stream that is not coming.
	if (!(await waitForMediaStream())) {
		return { type: "failed" }
	}

	const contentType = allowedMediaContentType(item)

	if (contentType === null) {
		return { type: "failed" }
	}

	return await videoThumb(item.data.uuid, () => previewStreamUrl(narrowToAnyFile(item), driveItemName(item), contentType), signal)
}

const SVG_RENDER_TIMEOUT_MS = 10_000

// Two renders at a time: an svg's layout and paint run on the main thread, where nothing can interrupt
// them, so a costly document never has more than one other beside it.
const svgRenderGate = new Semaphore(2)

async function inSvgRenderSlot<T>(render: () => Promise<T>): Promise<T> {
	await svgRenderGate.acquire()

	try {
		return await render()
	} finally {
		svgRenderGate.release()
	}
}

// Rasterises an svg document into a thumbnail. Only ever through an <img>: the SVG spec's secure mode
// for images runs no script, fires no event handler and fetches no external resource, so the markup
// never has to be sanitised to be safe (prepareSvgThumb refuses the entity bombs that mode does not
// cover). The blob URL is same-origin, so the canvas stays readable, except where an engine taints it
// for an svg anyway (Safari, for a <foreignObject>): that is a settled "unsupported", not a failure.
// Drawn at the thumbnail's own size, so the vector is rasterised once, crisply, at the size shown.
export async function rasterizeSvgThumb(text: string): Promise<ThumbGenerationResult> {
	const prepared = prepareSvgThumb(text, THUMB_MAX_DIM)

	if (prepared.type === "rejected") {
		return { type: "unavailable", reason: prepared.reason }
	}

	const result = await inSvgRenderSlot(() =>
		runTimeout<ThumbGenerationResult>(async defer => {
			const url = URL.createObjectURL(new Blob([prepared.markup], { type: "image/svg+xml" }))

			defer(() => {
				URL.revokeObjectURL(url)
			})

			const image = new Image(prepared.width, prepared.height)

			image.src = url

			try {
				await image.decode()
			} catch {
				return { type: "unavailable", reason: "corrupt" }
			}

			const canvas = new OffscreenCanvas(prepared.width, prepared.height)
			const ctx = canvas.getContext("2d")

			if (ctx === null) {
				throw new Error("could not create an OffscreenCanvas 2D context")
			}

			ctx.drawImage(image, 0, 0, prepared.width, prepared.height)

			let blob: Blob

			try {
				blob = await encodeCanvasThumb(canvas, { alpha: true })
			} catch (e) {
				if (e instanceof DOMException && e.name === "SecurityError") {
					return { type: "unavailable", reason: "unsupported" }
				}

				throw e
			}

			return { type: "bytes", bytes: new Uint8Array(await blob.arrayBuffer()) }
		}, SVG_RENDER_TIMEOUT_MS)
	)

	if (!result.success) {
		log.warn("thumb-generators", "rasterizeSvgThumb failed", result.error)

		return { type: "failed" }
	}

	return result.data
}

// Small by construction (THUMB_SVG_SIZE_GATE), so the whole document is read like a pdf's: the
// rasteriser needs the markup, not a stream. Once the markup is in hand the render always runs.
export const generateSvgThumb: ThumbGenerator = async (item, signal) => {
	let bytes: Uint8Array

	try {
		bytes = await downloadWholeFile(item, signal)
	} catch (e) {
		if (!signal.aborted) {
			log.warn("thumb-generators", "generateSvgThumb: download failed", item.data.uuid, e)
		}

		return { type: "failed" }
	}

	return await rasterizeSvgThumb(new TextDecoder().decode(bytes))
}

// One pdf.js worker shared by every PDF thumbnail, instead of one spun up and torn down per file.
// Passed to getDocument explicitly, so a task's destroy() ends only its own document and never the
// worker (pdf.js destroys only a worker it created itself), while pdfViewer.tsx's previews keep
// their own. Torn down once no generation has used it for a while.
const PDF_THUMB_WORKER_IDLE_MS = 30_000

let pdfThumbWorker: IdleResource<PDFWorker> | null = null

// Page 1 of a whole pdf, drawn into a thumbnail. Both arms share it: the drive-side one downloads the
// bytes, the upload warm reads them from the local file.
async function renderPdfThumb(bytes: Uint8Array, uuid: string): Promise<ThumbGenerationResult> {
	// Mirrors pdfViewer.tsx's own worker-src setup (duplicated rather than imported: that file is a
	// React component this module must not depend on). Read when the shared worker is constructed.
	GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.mjs", import.meta.url).href

	pdfThumbWorker ??= idleResource(
		() => new PDFWorker(),
		worker => {
			worker.destroy()
		},
		PDF_THUMB_WORKER_IDLE_MS
	)

	return await pdfThumbWorker.use<ThumbGenerationResult>(async worker => {
		const task = getDocument({ data: bytes, worker })

		try {
			// No onPassword handler is registered — pdf.js rejects task.promise with the password exception
			// instead of waiting on a handler that will never answer (verified against the installed 6.1.200
			// source), so a password-protected file fails this generation promptly rather than hanging.
			const doc = await task.promise
			const page = await doc.getPage(1)
			const baseViewport = page.getViewport({ scale: 1 })
			const fitted = fitWithin(baseViewport.width, baseViewport.height, THUMB_MAX_DIM)
			const viewport = page.getViewport({ scale: fitted.width / baseViewport.width })

			const canvas = document.createElement("canvas")

			canvas.width = fitted.width
			canvas.height = fitted.height

			const renderTask = page.render({ canvas, viewport })

			await renderTask.promise

			const blob = await encodeCanvasThumb(canvas)

			return { type: "bytes", bytes: new Uint8Array(await blob.arrayBuffer()) }
		} catch (e) {
			log.warn("thumb-generators", "renderPdfThumb: render failed", uuid, e)
			// pdf.worker is its own file: a deploy that changed it fails documents in older tabs.
			recoverIfNewerBuild()

			return { type: "failed" }
		} finally {
			await task.destroy()
		}
	})
}

// Once the bytes are in hand the render always runs: page 1 costs far less than the download did.
export const generatePdfThumb: ThumbGenerator = async (item, signal) => {
	let bytes: Uint8Array

	try {
		bytes = await downloadWholeFile(item, signal)
	} catch (e) {
		if (!signal.aborted) {
			log.warn("thumb-generators", "generatePdfThumb: download failed", item.data.uuid, e)
		}

		return { type: "failed" }
	}

	return await renderPdfThumb(bytes, item.data.uuid)
}

// Module scope, not inside a function: runs exactly once per module evaluation (mirrors
// the drive.newDirectory def in features/drive/lib/keymap.ts). features/drive/lib/thumbnails.ts (the service)
// deliberately never imports this module itself — it already exposes registerThumbGenerator as a
// seam specifically so it doesn't need to know these generators exist, and importing back would cycle
// — so whichever consumer wants thumbnails (sdk/video/pdf/svg) must import this module at least once,
// even just for this side effect, before requesting one; until then getThumbnailUrl's own
// unregistered-category path (a clean null, never a throw) is all any item resolves to.
registerThumbGenerator("sdk", generateSdkThumb)
registerThumbGenerator("video", generateVideoThumb)
registerThumbGenerator("pdf", generatePdfThumb)
registerThumbGenerator("svg", generateSvgThumb)
