import { runTimeout } from "@filen/utils"
import { sdkApi } from "@/lib/sdk/client"
import { runOp } from "@/lib/actions/outcome"
import { log } from "@/lib/log"
import { narrowToAnyFile } from "@/features/drive/lib/download"
import { registerThumbGenerator, type ThumbGenerator } from "@/features/drive/lib/thumbnails"
import { THUMB_MAX_DIM } from "@/features/drive/lib/thumbnails.logic"
import { fitWithin, encodeCanvasThumb } from "@/features/drive/lib/thumbGenerators.logic"
import { transformHeicBytes } from "@/features/preview/lib/heicTransform"
import { previewStreamUrl, isMediaStreamAvailable } from "@/features/preview/lib/previewStream"
import { allowedMediaContentType } from "@/features/preview/lib/mediaType"
import { type BaseFileItem } from "@/features/drive/lib/item"

// heic/pdf both pull the whole file into memory through the same buffered download the preview
// overlay uses (usePreviewBytes). There is no unmount to hook a cancellation into here (a generator
// is a one-shot promise the service's own Semaphore/dedupe gate around, not a component) so the
// minted token only ever satisfies downloadFileBytes' own signature — the worker's previewAborts
// entry for it is dropped on this same call's own settle regardless of whether anything ever calls
// cancelPreviewDownload.
async function downloadWholeFile(item: BaseFileItem): Promise<Uint8Array> {
	const file = narrowToAnyFile(item)
	const token = crypto.randomUUID()

	return await runOp(sdkApi.downloadFileBytes(file, token))
}

// Persisting the generated bytes (storeThumbnail) is NOT this generator's job — features/drive/lib/thumbnails.ts's
// own generate() already does that once, uniformly, for whatever any registered generator returns. A
// second persist call here would double-write the same uuid to OPFS on every client-generated thumbnail.
export const generateHeicThumb: ThumbGenerator = async item => {
	let bytes: Uint8Array

	try {
		bytes = await downloadWholeFile(item)
	} catch (e) {
		log.warn("thumb-generators", "generateHeicThumb: download failed", item.data.uuid, e)

		return null
	}

	try {
		const blob = await transformHeicBytes(bytes, { maxDimension: THUMB_MAX_DIM })

		return new Uint8Array(await blob.arrayBuffer())
	} catch (e) {
		log.warn("thumb-generators", "generateHeicThumb: transform failed", item.data.uuid, e)

		return null
	}
}

// Resolves once `event` fires, or rejects if the element errors first — a corrupt/unplayable stream
// must fail promptly rather than sit until runTimeout's own ceiling.
function waitForVideoEvent(video: HTMLVideoElement, event: "loadeddata" | "seeked"): Promise<void> {
	return new Promise((resolve, reject) => {
		const cleanup = () => {
			video.removeEventListener(event, onEvent)
			video.removeEventListener("error", onError)
		}
		const onEvent = () => {
			cleanup()
			resolve()
		}
		const onError = () => {
			cleanup()
			reject(new Error(`video element errored before ${event}`))
		}

		video.addEventListener(event, onEvent, { once: true })
		video.addEventListener("error", onError, { once: true })
	})
}

const VIDEO_GENERATE_TIMEOUT_MS = 15_000

// isMediaStreamAvailable/allowedMediaContentType are cheap synchronous gates checked BEFORE the
// runTimeout below, so an environment that can never stream (SW not yet controlling the tab, or an
// item whose own mime never clears the inline allowlist) fails instantly instead of occupying a
// semaphore slot for the full 15s ceiling for no reason.
export const generateVideoThumb: ThumbGenerator = async item => {
	if (!isMediaStreamAvailable()) {
		return null
	}

	const contentType = allowedMediaContentType(item)

	if (contentType === null) {
		return null
	}

	// runTimeout races a timer against this whole callback but cannot actually abort a still-running
	// video/event-listener chain if it loses the race (verified against @filen/utils' own
	// implementation: the deferred cleanup below only runs once THIS callback itself settles) — an
	// unplayable stream that never fires loadeddata/seeked/error leaves a listener chain pending in
	// the background past the 15s return. That is an accepted, bounded cost: the SW's own pending-
	// registration table is capped at 32 entries and oldest-evicts, so it cannot accumulate across a
	// session even if this happens repeatedly.
	const result = await runTimeout(async defer => {
		const file = narrowToAnyFile(item)
		const name = item.data.decryptedMeta?.name ?? item.data.uuid
		const url = await previewStreamUrl(file, name, contentType)

		const video = document.createElement("video")

		video.muted = true
		video.playsInline = true
		video.preload = "auto"
		video.src = url

		defer(() => {
			video.src = ""
			video.load()
		})

		await waitForVideoEvent(video, "loadeddata")

		// An indeterminate duration (NaN — e.g. a stream with no known Content-Length) falls back to
		// frame 0, which is already showing once loadeddata fires: seeking to the position the video is
		// already at would never fire `seeked`, hanging until the outer timeout.
		const seekTo = Number.isFinite(video.duration) ? Math.min(1, video.duration / 2) : 0

		if (seekTo > 0) {
			video.currentTime = seekTo

			await waitForVideoEvent(video, "seeked")
		}

		const { width, height } = fitWithin(video.videoWidth, video.videoHeight, THUMB_MAX_DIM)
		const canvas = new OffscreenCanvas(width, height)
		const ctx = canvas.getContext("2d")

		if (ctx === null) {
			throw new Error("could not create an OffscreenCanvas 2D context")
		}

		ctx.drawImage(video, 0, 0, width, height)

		const blob = await encodeCanvasThumb(canvas)

		return new Uint8Array(await blob.arrayBuffer())
	}, VIDEO_GENERATE_TIMEOUT_MS)

	if (!result.success) {
		log.warn("thumb-generators", "generateVideoThumb failed", item.data.uuid, result.error)

		return null
	}

	return result.data
}

export const generatePdfThumb: ThumbGenerator = async item => {
	let bytes: Uint8Array

	try {
		bytes = await downloadWholeFile(item)
	} catch (e) {
		log.warn("thumb-generators", "generatePdfThumb: download failed", item.data.uuid, e)

		return null
	}

	// Lazy: keeps pdf.js's ~1 MB bundle out of every session that never opens or generates a PDF
	// thumbnail — pdfViewer.tsx can import it statically because that whole component is itself
	// route/lazy-split, which this plain module is not.
	const { getDocument, GlobalWorkerOptions } = await import("pdfjs-dist")

	// Mirrors pdfViewer.tsx's own worker-src setup (duplicated rather than imported: that file is a
	// React component this module must not depend on). A STRING workerSrc gives every getDocument()
	// call its own dedicated worker, so this task's destroy() below can never tear down a document a
	// concurrent preview or generation still has open.
	GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.mjs", import.meta.url).href

	const task = getDocument({ data: bytes })

	try {
		// No onPassword handler is registered — pdf.js rejects task.promise with the password exception
		// instead of waiting on a handler that will never answer (verified against the installed 6.1.200
		// source), so a password-protected file fails this generation promptly rather than hanging.
		const doc = await task.promise
		const page = await doc.getPage(1)
		const baseViewport = page.getViewport({ scale: 1 })
		const fitted = fitWithin(baseViewport.width, baseViewport.height, THUMB_MAX_DIM)
		const viewport = page.getViewport({ scale: fitted.width / baseViewport.width })

		const canvas = document.createElement("canvas")

		canvas.width = fitted.width
		canvas.height = fitted.height

		const renderTask = page.render({ canvas, viewport })

		await renderTask.promise

		const blob = await encodeCanvasThumb(canvas)

		return new Uint8Array(await blob.arrayBuffer())
	} catch (e) {
		log.warn("thumb-generators", "generatePdfThumb: render failed", item.data.uuid, e)

		return null
	} finally {
		await task.destroy()
	}
}

// Module scope, not inside a function: runs exactly once per module evaluation (mirrors
// newDirectory.tsx's own module-scope registerAction call). features/drive/lib/thumbnails.ts (the service)
// deliberately never imports this module itself — it already exposes registerThumbGenerator as a
// seam specifically so it doesn't need to know these three exist, and importing back would cycle —
// so whichever consumer wants client-generated (heic/video/pdf) thumbnails must import this module at
// least once, even just for this side effect, before requesting one; until then getThumbnailUrl's own
// unregistered-category path (a clean null, never a throw) is all a heic/video/pdf item resolves to.
registerThumbGenerator("heic", generateHeicThumb)
registerThumbGenerator("video", generateVideoThumb)
registerThumbGenerator("pdf", generatePdfThumb)
