// The account API stores the personal-info "country" field as a plain English name string (no ISO
// 3166 region code), so this list cannot be localized via Intl.DisplayNames — it stays a
// non-translated data constant. Matches mobile's own personal-info picker exactly, dependent
// territories included (features/settings/constants.ts's flat `countries` export, not its unused
// `sovereignCountries` derivative), so both clients write identical values for the same place.
export const COUNTRIES: readonly string[] = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Democratic Republic of the Congo",
	"Republic of the Congo",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"North Korea",
	"South Korea",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"North Macedonia",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Romania",
	"Russia",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands",
	"American Samoa",
	"Anguilla",
	"Antarctica",
	"Aruba",
	"Bermuda",
	"Bonaire, Sint Eustatius and Saba",
	"Bouvet Island",
	"British Indian Ocean Territory",
	"British Virgin Islands",
	"Cayman Islands",
	"Christmas Island",
	"Cocos (Keeling) Islands",
	"Cook Islands",
	"Curaçao",
	"Falkland Islands",
	"Faroe Islands",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories",
	"Gibraltar",
	"Greenland",
	"Guadeloupe",
	"Guam",
	"Guernsey",
	"Heard Island and McDonald Islands",
	"Hong Kong",
	"Isle of Man",
	"Jersey",
	"Macao",
	"Martinique",
	"Mayotte",
	"Montserrat",
	"New Caledonia",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands",
	"Pitcairn Islands",
	"Puerto Rico",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Martin",
	"Saint Pierre and Miquelon",
	"Sint Maarten",
	"South Georgia and the South Sandwich Islands",
	"Svalbard and Jan Mayen",
	"Tokelau",
	"Turks and Caicos Islands",
	"United States Minor Outlying Islands",
	"U.S. Virgin Islands",
	"Wallis and Futuna",
	"Western Sahara"
].sort((a, b) => a.localeCompare(b))

// A blank/unset country is a valid, saved state (see formStateToUpdateInfo's trim-to-undefined
// convention) — this is the closed-list check the dropdown validates against: any value that is
// either "" (unset) or an exact member of COUNTRIES.
export function isValidCountry(value: string): boolean {
	return value === "" || COUNTRIES.includes(value)
}

// The stored country is free text on the wire and other clients may hold a value this closed list
// does not know. `update_personal_info` is a whole-record write, so a value the dropdown cannot
// represent would be posted back as "not set" and wiped the next time any unrelated field is
// saved — the option list therefore carries the current value even when it is off-list.
export function countryOptions(current: string): readonly string[] {
	if (isValidCountry(current)) {
		return COUNTRIES
	}

	return [...COUNTRIES, current].sort((a, b) => a.localeCompare(b))
}
