// Browser-only download primitive for small, client-generated bytes (a plain-text export, a
// client-built zip archive, ...): a throwaway object URL clicked via a detached anchor, revoked
// right after. `@filen/utils` ships no DOM helpers (deliberately runtime-agnostic — this touches
// document/Blob/URL, none of which exist under Node or React Native), so it stays local. Shared by
// the security-settings export flows (features/settings/lib/downloadTextFile.ts) and notes export
// (features/notes/lib/export.ts) — one anchor-click convention for client-generated content, never
// duplicated. NOT the drive download path: a real vault file streams through saveDownload.ts's FSA/
// service-worker mechanism instead, since it can be arbitrarily large and needs progress reporting;
// this is for bytes already fully in memory. Not unit-tested: this project's vitest config runs
// environment:"node" (no DOM — see vitest.config.ts), so document/URL.createObjectURL do not exist
// there; verified instead via e2e (downloads.spec.ts's own waitForEvent("download") convention).
export function downloadBlob(filename: string, blob: Blob): void {
	const url = URL.createObjectURL(blob)
	try {
		const anchor = document.createElement("a")
		anchor.href = url
		anchor.download = filename
		anchor.click()
	} finally {
		URL.revokeObjectURL(url)
	}
}
