name: Publish @filen/utils to NPM

on:
  release:
    types: [published]

concurrency:
  group: 'npm-publish-utils'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.release.tag_name, '@filen/utils') || contains(github.event.release.name, '@filen/utils')
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        working-directory: packages/filen-utils
        run: pnpm install --frozen-lockfile --filter @filen/utils
      - name: Build
        working-directory: packages/filen-utils
        run: pnpm run build
      - name: Configure the registry for publishing
        working-directory: packages/filen-utils
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc
      - name: Publish
        working-directory: packages/filen-utils
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Cleanup
        working-directory: packages/filen-utils
        run: rm -rf ~/.npmrc
