name: Test (filen-utils)

on:
  workflow_dispatch:

  push:
    paths:
      - 'packages/filen-utils/**/*'

  pull_request:
    paths:
      - 'packages/filen-utils/**/*'

concurrency:
  group: 'test-utils'
  cancel-in-progress: true

jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        working-directory: packages/filen-utils
        run: npm install --package-lock-only && npm ci
      - name: Test
        working-directory: packages/filen-utils
        run: npm test
