name: Typecheck

on:
  workflow_dispatch:

  push:
    paths:
      - 'packages/filen-web/**'
      - 'packages/filen-mobile/**'
      - 'packages/filen-utils/**'

  pull_request:
    paths:
      - 'packages/filen-web/**'
      - 'packages/filen-mobile/**'
      - 'packages/filen-utils/**'

concurrency:
  group: 'typecheck'
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      filen-web: ${{ steps.filter.outputs.filen-web }}
      filen-mobile: ${{ steps.filter.outputs.filen-mobile }}
      filen-utils: ${{ steps.filter.outputs.filen-utils }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            filen-web:
              - 'packages/filen-web/**'
            filen-mobile:
              - 'packages/filen-mobile/**'
            filen-utils:
              - 'packages/filen-utils/**'

  typecheck-web:
    needs: changes
    if: needs.changes.outputs.filen-web == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: packages/filen-web/package-lock.json
      - name: Install dependencies
        working-directory: packages/filen-web
        run: npm install --package-lock-only --no-workspaces && npm ci
      - name: Typecheck
        working-directory: packages/filen-web
        run: npm run typecheck
  typecheck-mobile:
    needs: changes
    if: needs.changes.outputs.filen-mobile == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: packages/filen-mobile/package-lock.json
      - name: Install patch-package
        run: npm install -g patch-package
      - name: Install dependencies
        working-directory: packages/filen-mobile
        run: npm install --package-lock-only && npm ci
      - name: Typecheck
        working-directory: packages/filen-mobile
        run: npm run typecheck
  typecheck-utils:
    needs: changes
    if: needs.changes.outputs.filen-utils == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: packages/filen-utils/package-lock.json
      - name: Install dependencies
        working-directory: packages/filen-utils
        run: npm install --package-lock-only --no-workspaces && npm ci
      - name: Typecheck
        working-directory: packages/filen-utils
        run: npm run typecheck
